"""
main.py -- FastAPI app entry point. Serves three things behind one origin
(avoids CORS entirely, so the dashboard's fetch() calls can use plain
relative paths and automatically include the session cookie):

  1. POST/GET /api/*   -- auth + dashboard data endpoints (routers/)
  2. GET /login        -- a small, separate static login page (does NOT
                           touch interactive_dashboard_template.html)
  3. GET /dashboard     -- the existing dashboard HTML, served ONLY to an
                           authenticated session (unauthenticated requests
                           are redirected to /login) -- the shell itself
                           requires login, not just the data calls it makes.

Run with: uvicorn main:app --host 0.0.0.0 --port 8000
(behind a reverse proxy / real TLS termination in production -- session
cookies are set `secure=True`, which browsers refuse to send back over
plain HTTP).

Full OpenAPI schema (response models included) is auto-generated by
FastAPI at GET /openapi.json, with interactive docs at /docs and /redoc.
"""

import logging
import os
import sys
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Request
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import FileResponse, JSONResponse, RedirectResponse

# NOTE: Codes/ and Codes/api/ each have their own config.py (DatabaseSettings
# vs. Settings -- deliberately separate, sync-ETL vs. async-API concerns).
# _API_DIR MUST be searched before Codes/ or `import config` here would
# resolve to the wrong one -- insert(0, ...) puts api/ first; append() puts
# Codes/ last, consulted only as a fallback (for logging_config, which
# only exists there).
_API_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _API_DIR)
sys.path.append(os.path.dirname(_API_DIR))
from config import Settings  # noqa: E402
from db import Database  # noqa: E402
from deps import get_current_user  # noqa: E402
from logging_config import configure_logging  # noqa: E402
from routers import auth, dashboard  # noqa: E402
from security import SecurityService  # noqa: E402

configure_logging()
logger = logging.getLogger(__name__)

CODES_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DASHBOARD_HTML_PATH = os.path.join(CODES_DIR, "interactive_dashboard_template.html")
LOGIN_HTML_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static", "login.html")


# Warmed once at startup (see Database.warm_up()'s docstring for why a
# fresh connection's first hit against these views is measurably slower
# than later ones) -- each dashboard payload query run twice, concurrently,
# so roughly 8 pooled connections are pre-warmed rather than just 4: a
# single dashboard page load fires all 4 of these via Promise.all(), and a
# browser's own connection-level parallelism means those 4 concurrent HTTP
# requests don't reliably land on the same 4 DB connections warmed by a
# single pass.
_WARM_UP_QUERIES = (
    "SELECT * FROM mv_dashboard_rows",
    "SELECT * FROM mv_dashboard_tat_rows",
    "SELECT * FROM mv_dashboard_creation_time_rows",
    "SELECT * FROM mv_dashboard_status_rows",
) * 2

# Never a real app_sessions.id (that column is always a real gen_random_
# uuid()) -- used only to warm the auth-check query's per-connection
# prepare cost at startup (Database.warm_up_auth_check()) without ever
# matching, and therefore never touching, a real session row.
_AUTH_WARM_UP_TOKEN = "00000000-0000-0000-0000-000000000000"
_AUTH_WARM_UP_CALLS = 10  # matches db.py's pool_size


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Creates the app's single Database/SecurityService instances once at
    startup (not per-request, not a lazily-initialized global), warms the
    connection pool, and disposes the async engine cleanly on shutdown."""
    settings = Settings.from_env()
    app.state.db = Database(settings)
    app.state.security = SecurityService(
        idle_timeout_hours=settings.session_idle_timeout_hours,
        absolute_max_days=settings.session_absolute_max_days,
        cookie_secure=settings.session_cookie_secure,
    )
    await app.state.db.warm_up(_WARM_UP_QUERIES)
    await app.state.db.warm_up_auth_check(
        app.state.security, _AUTH_WARM_UP_TOKEN, _AUTH_WARM_UP_CALLS,
    )
    logger.info("Application startup complete.")
    yield
    await app.state.db.dispose()
    logger.info("Application shutdown complete.")


app = FastAPI(
    title="iSend Transaction Dashboard API",
    description=(
        "Middleware between the transaction dashboard HTML shell and the "
        "business_report materialized view -- authentication plus filtered, "
        "server-side-aggregated dashboard data endpoints.\n\n"
        "This page (`/docs`) documents the REST API itself -- request/"
        "response shapes for the endpoints below. For everything else, see "
        "the project's own docs (in the repo, not served here):\n\n"
        "- **README.md** -- setup and run instructions\n"
        "- **WORKFLOW.md** -- how data flows through the whole system, as "
        "diagrams\n"
        "- **DASHBOARD_GUIDE.md** -- a plain-language guide to using the "
        "dashboard itself (non-technical)\n"
        "- **CLAUDE.md** -- full architecture and every design decision, "
        "for developers"
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.include_router(auth.router)
app.include_router(dashboard.router)

# The dashboard payload endpoints (/api/rows, /api/creation_time_rows
# especially) return 47-60MB of JSON -- highly repetitive (the same column
# names repeated across tens of thousands of near-identical objects), so it
# compresses extremely well. Confirmed directly this was previously shipped
# fully uncompressed: no GZipMiddleware here and no `encode` directive in
# the Caddyfile, over a link whose round-trip latency is already high (this
# app's RDS host and its viewers are far apart) -- on a latency- and
# bandwidth-constrained connection, sending 5-10x more bytes than necessary
# costs real, user-visible seconds. Caddy (Caddyfile) also compresses at
# the reverse-proxy hop; this covers direct-to-uvicorn access too (e.g.
# local dev without Caddy in front). compresslevel=6 (zlib/nginx's own
# default), not Starlette's default of 9 -- confirmed directly that 9 costs
# ~7x the CPU time for a ~47MB payload (2.3s vs 0.3s) for only ~6% smaller
# output, and GZipMiddleware compresses synchronously in the request
# coroutine (not offloaded to a thread), so that time blocks this single
# event loop for every OTHER concurrent request too -- worth confirming
# level 9 wasn't actually making concurrent dashboard loads worse, not
# better, before assuming "more compression always helps" on a
# latency-bound, not bandwidth-starved, connection.
app.add_middleware(GZipMiddleware, minimum_size=1024, compresslevel=6)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Last-resort handler: logs the full traceback server-side and returns
    a generic 500 -- never leaks internal error detail (query text,
    stack frames) to the client."""
    logger.exception("Unhandled exception on %s %s", request.method, request.url.path)
    return JSONResponse(status_code=500, content={"detail": "Internal server error"})


@app.get("/", include_in_schema=False)
def root() -> RedirectResponse:
    return RedirectResponse(url="/dashboard")


@app.get("/login", include_in_schema=False)
def login_page() -> FileResponse:
    return FileResponse(LOGIN_HTML_PATH)


@app.get("/dashboard", include_in_schema=False)
async def dashboard_page(request: Request):
    """
    Unlike the API's data endpoints (which return a 401 JSON body on an
    expired/missing session via the get_current_user dependency), a request
    for the page itself should redirect to the login PAGE instead -- so
    get_current_user is called directly here, and its HTTPException is
    caught and turned into a redirect rather than propagating as an error
    response.
    """
    try:
        await get_current_user(
            request, db=request.app.state.db, security=request.app.state.security,
        )
    except HTTPException:
        return RedirectResponse(url="/login")
    return FileResponse(DASHBOARD_HTML_PATH)
